version: '3'
services:
  notification-server:
    build: ./notificationServer
    ports:
      - "8080:8080"
    depends_on:
      - notification-frontend

  notification-frontend:
    build: ./notificationfront
    ports:
      - "3000:3000"
