# Use the official OpenJDK image as a parent image
FROM openjdk:22-jdk-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the packaged jar file into the container at /app
COPY ./target/notificationServer-0.0.1-SNAPSHOT.jar /app/notificationServer.jar

# Expose the port that your Spring Boot application uses (default is 8080)
EXPOSE 8080

# Run the jar file
CMD ["java", "-jar", "/app/notificationServer.jar"]
